import type { CatalogItem, FurnitureCategory } from '../types/spatial'

export const CATEGORY_LABELS: Record<FurnitureCategory, string> = {
  beds: 'Beds',
  sofas: 'Sofas',
  chairs: 'Chairs',
  tables: 'Tables',
  desks: 'Desks',
  storage: 'Storage',
  rugs: 'Rugs',
  lighting: 'Lighting',
  plants: 'Plants',
}

export const CATEGORY_ORDER: FurnitureCategory[] = [
  'beds',
  'sofas',
  'chairs',
  'tables',
  'desks',
  'storage',
  'rugs',
  'lighting',
  'plants',
]

export const FURNITURE_CATALOG: CatalogItem[] = [
  {
    type: 'twin-bed',
    name: 'Twin Bed',
    category: 'beds',
    width: 38,
    depth: 75,
    height: 24,
    color: '#E6D9CB',
    renderer: 'bed',
  },
  {
    type: 'queen-bed',
    name: 'Queen Bed',
    category: 'beds',
    width: 60,
    depth: 80,
    height: 24,
    color: '#E6D9CB',
    renderer: 'bed',
  },
  {
    type: 'king-bed',
    name: 'King Bed',
    category: 'beds',
    width: 76,
    depth: 80,
    height: 24,
    color: '#E6D9CB',
    renderer: 'bed',
  },
  {
    type: 'sofa-2',
    name: '2-Seat Sofa',
    category: 'sofas',
    width: 68,
    depth: 34,
    height: 32,
    color: '#8A8178',
    renderer: 'sofa',
  },
  {
    type: 'sofa-3',
    name: '3-Seat Sofa',
    category: 'sofas',
    width: 84,
    depth: 36,
    height: 32,
    color: '#7E766C',
    renderer: 'sofa',
  },
  {
    type: 'armchair',
    name: 'Armchair',
    category: 'sofas',
    width: 34,
    depth: 32,
    height: 32,
    color: '#9A8B7A',
    renderer: 'armchair',
  },
  {
    type: 'desk-chair',
    name: 'Desk Chair',
    category: 'chairs',
    width: 22,
    depth: 22,
    height: 36,
    color: '#4E4A45',
    renderer: 'desk-chair',
  },
  {
    type: 'dining-chair',
    name: 'Dining Chair',
    category: 'chairs',
    width: 20,
    depth: 20,
    height: 36,
    color: '#C4B09A',
    renderer: 'dining-chair',
  },
  {
    type: 'lounge-chair',
    name: 'Lounge Chair',
    category: 'chairs',
    width: 30,
    depth: 34,
    height: 32,
    color: '#A09080',
    renderer: 'armchair',
  },
  {
    type: 'dining-table',
    name: 'Dining Table',
    category: 'tables',
    width: 60,
    depth: 36,
    height: 30,
    color: '#C4B196',
    renderer: 'table',
  },
  {
    type: 'round-dining-table',
    name: 'Round Dining Table',
    category: 'tables',
    width: 42,
    depth: 42,
    height: 30,
    color: '#C4B196',
    renderer: 'table',
    shape: 'circle',
  },
  {
    type: 'oval-dining-table',
    name: 'Oval Dining Table',
    category: 'tables',
    width: 72,
    depth: 40,
    height: 30,
    color: '#C4B196',
    renderer: 'table',
    shape: 'oval',
  },
  {
    type: 'coffee-table',
    name: 'Coffee Table',
    category: 'tables',
    width: 42,
    depth: 24,
    height: 16,
    color: '#CDB79A',
    renderer: 'table',
  },
  {
    type: 'side-table',
    name: 'Side Table',
    category: 'tables',
    width: 20,
    depth: 20,
    height: 22,
    color: '#D2C0A8',
    renderer: 'table',
  },
  {
    type: 'round-side-table',
    name: 'Round Side Table',
    category: 'tables',
    width: 24,
    depth: 24,
    height: 22,
    color: '#D2C0A8',
    renderer: 'table',
    shape: 'circle',
  },
  {
    type: 'writing-desk',
    name: 'Writing Desk',
    category: 'desks',
    width: 48,
    depth: 24,
    height: 30,
    color: '#C6B094',
    renderer: 'desk',
  },
  {
    type: 'large-desk',
    name: 'Large Desk',
    category: 'desks',
    width: 60,
    depth: 30,
    height: 30,
    color: '#C6B094',
    renderer: 'desk',
  },
  {
    type: 'round-desk',
    name: 'Round Desk',
    category: 'desks',
    width: 48,
    depth: 48,
    height: 30,
    color: '#C6B094',
    renderer: 'desk',
    shape: 'circle',
  },
  {
    type: 'l-desk',
    name: 'L-Shaped Desk',
    category: 'desks',
    width: 60,
    depth: 48,
    height: 30,
    color: '#C6B094',
    renderer: 'desk',
    shape: 'lShape',
    shapeData: { thickness: 24, returnLength: 48, returnSide: 'left' },
  },
  {
    type: 'dresser',
    name: 'Dresser',
    category: 'storage',
    width: 60,
    depth: 20,
    height: 32,
    color: '#B89A78',
    renderer: 'dresser',
  },
  {
    type: 'bookshelf',
    name: 'Bookshelf',
    category: 'storage',
    width: 32,
    depth: 14,
    height: 72,
    color: '#A88868',
    renderer: 'bookshelf',
  },
  {
    type: 'nightstand',
    name: 'Nightstand',
    category: 'storage',
    width: 20,
    depth: 16,
    height: 24,
    color: '#C4A882',
    renderer: 'nightstand',
  },
  {
    type: 'large-rug',
    name: 'Large Rug',
    category: 'rugs',
    width: 96,
    depth: 120,
    height: 0.5,
    color: '#D7CBB8',
    renderer: 'rug',
  },
  {
    type: 'medium-rug',
    name: 'Medium Rug',
    category: 'rugs',
    width: 60,
    depth: 90,
    height: 0.5,
    color: '#D2C2AE',
    renderer: 'rug',
  },
  {
    type: 'round-rug',
    name: 'Round Rug',
    category: 'rugs',
    width: 72,
    depth: 72,
    height: 0.5,
    color: '#D7CBB8',
    renderer: 'rug',
    shape: 'circle',
  },
  {
    type: 'oval-rug',
    name: 'Oval Rug',
    category: 'rugs',
    width: 72,
    depth: 48,
    height: 0.5,
    color: '#D2C2AE',
    renderer: 'rug',
    shape: 'oval',
  },
  {
    type: 'floor-lamp',
    name: 'Floor Lamp',
    category: 'lighting',
    width: 18,
    depth: 18,
    height: 62,
    color: '#E8DCC8',
    renderer: 'lamp',
  },
  {
    type: 'table-lamp',
    name: 'Table Lamp',
    category: 'lighting',
    width: 12,
    depth: 12,
    height: 22,
    color: '#EFE4D4',
    renderer: 'lamp',
  },
  {
    type: 'large-plant',
    name: 'Large Plant',
    category: 'plants',
    width: 24,
    depth: 24,
    height: 60,
    color: '#6F8A68',
    renderer: 'plant',
  },
  {
    type: 'small-plant',
    name: 'Small Plant',
    category: 'plants',
    width: 12,
    depth: 12,
    height: 24,
    color: '#7B9570',
    renderer: 'plant',
  },
]

const catalogByType = new Map(FURNITURE_CATALOG.map((item) => [item.type, item]))

export function getCatalogItem(type: string): CatalogItem | undefined {
  return catalogByType.get(type)
}

export function catalogByCategory(): { category: FurnitureCategory; items: CatalogItem[] }[] {
  return CATEGORY_ORDER.map((category) => ({
    category,
    items: FURNITURE_CATALOG.filter((item) => item.category === category),
  }))
}
